import React, { useRef } from "react";
import { Button } from "primereact/button";
import { useReactToPrint } from "react-to-print";
// import "./../../assets/css/report.scss";

const OvertimePage = () => {
    const componentRef = useRef();

    const handlePrint = useReactToPrint({
        content: () => componentRef.current,
    });

    return (
        <div className="grid">
            <div className="col-12">
                <div className="card">
                    <h5>Report Page</h5>                    
                    <Button type="button" onClick={handlePrint} label="Print" icon="pi pi-print" className="mb-3" />

                    <div  ref={componentRef}>
                        <div className="page">
                            <div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                                <p>
                                    Suspendisse potenti nullam ac tortor. Suspendisse in est ante in nibh. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas sed tempus urna et. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Elit duis tristique sollicitudin nibh sit amet commodo. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Nunc eget lorem dolor sed viverra ipsum. Est ullamcorper eget nulla facilisi etiam. Ac turpis egestas maecenas pharetra convallis posuere. Donec enim diam vulputate ut pharetra sit amet aliquam id.
                                </p>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                            </div>
                        </div>
                        <div className="page">
                            <div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                                <p>
                                    Suspendisse potenti nullam ac tortor. Suspendisse in est ante in nibh. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas sed tempus urna et. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Elit duis tristique sollicitudin nibh sit amet commodo. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Nunc eget lorem dolor sed viverra ipsum. Est ullamcorper eget nulla facilisi etiam. Ac turpis egestas maecenas pharetra convallis posuere. Donec enim diam vulputate ut pharetra sit amet aliquam id.
                                </p>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                            </div>
                        </div>
                        <div className="page">
                            <div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                                <p>
                                    Suspendisse potenti nullam ac tortor. Suspendisse in est ante in nibh. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas sed tempus urna et. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Elit duis tristique sollicitudin nibh sit amet commodo. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Nunc eget lorem dolor sed viverra ipsum. Est ullamcorper eget nulla facilisi etiam. Ac turpis egestas maecenas pharetra convallis posuere. Donec enim diam vulputate ut pharetra sit amet aliquam id.
                                </p>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Ac orci phasellus egestas tellus rutrum tellus. Risus at ultrices mi tempus imperdiet. Quam adipiscing vitae proin sagittis nisl rhoncus. Tortor posuere ac ut consequat semper. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Turpis massa tincidunt dui ut ornare. Erat nam at lectus urna duis convallis. Ultrices in iaculis nunc sed augue lacus. Nec sagittis aliquam malesuada bibendum arcu. Cras semper auctor neque vitae tempus quam pellentesque nec. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a.
                                </p>
                                <p>
                                    Pharetra diam sit amet nisl suscipit adipiscing bibendum. Morbi tempus iaculis urna id volutpat lacus laoreet non. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Tincidunt vitae semper quis lectus. Non sodales neque sodales ut etiam sit amet nisl purus. Non consectetur a erat nam at lectus urna. Eu non diam phasellus vestibulum lorem sed. Urna neque viverra justo nec ultrices dui. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. In cursus turpis massa tincidunt dui ut ornare. Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Et malesuada fames ac turpis egestas maecenas pharetra. Dui ut ornare lectus sit amet est placerat. Volutpat est velit egestas dui id ornare. Dui sapien eget mi proin sed libero. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.
                                </p>
                                <p>
                                    Tincidunt arcu non sodales neque sodales ut. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Posuere morbi leo urna molestie at. Consectetur libero id faucibus nisl tincidunt eget nullam non. Vivamus at augue eget arcu dictum varius. Non odio euismod lacinia at quis risus sed. Imperdiet proin fermentum leo vel orci. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Feugiat pretium nibh ipsum consequat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Massa id neque aliquam vestibulum morbi blandit cursus. Lectus arcu bibendum at varius vel pharetra vel. Facilisi morbi tempus iaculis urna. Aenean sed adipiscing diam donec adipiscing. Neque gravida in fermentum et sollicitudin. Netus et malesuada fames ac turpis egestas sed tempus urna. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Et pharetra pharetra massa massa ultricies mi quis. Cursus euismod quis viverra nibh cras pulvinar.
                                </p>
                                <p>
                                    Id porta nibh venenatis cras sed felis eget. Libero volutpat sed cras ornare arcu dui vivamus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Nisl rhoncus mattis rhoncus urna neque viverra. At lectus urna duis convallis convallis tellus id interdum velit. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Lectus quam id leo in vitae turpis massa. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Scelerisque purus semper eget duis at tellus. Nunc aliquet bibendum enim facilisis gravida neque convallis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

const comparisonFn = function (prevProps, nextProps) {
    return prevProps.location.pathname === nextProps.location.pathname;
};

export default React.memo(OvertimePage, comparisonFn);
